### ISSUE TITLE
Cant seem to run main.py code.

### ISSUE THREAD

**Issue by AdarshMJ** [kenshohara/video-classification-3d-cnn-pytorch#27]
Whenever I run the main.py code, I keep getting this error.

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from model import generate_model
  File "/Users/adarshjamadandi/Desktop/video-classification-3d-cnn-pytorch/model.py", line 4, in <module>
    from models import resnet, pre_act_resnet, wide_resnet, resnext, densenet
ImportError: No module named models

Please help me out!

**Comment by O-Givenchy** [comment]
i guess there is nothing wrong in the code . pls make sure u input the correct parameters before u run main.py code. especially the path of the PRETRAINED MODELS  :)

**Comment by Mohamad73** [comment]
I think it is because you are running it on python 2.7

**Comment by tuyunbin** [comment]
> I think it is because you are running it on python 2.7
Thank you, you are right,  and I sovled this problem when changing version of python to 3+
