### ISSUE TITLE
Error and Explanation of Generate_result_videos function

### ISSUE THREAD

**Issue by Mohamad73** [kenshohara/video-classification-3d-cnn-pytorch#33]
Hi, first I am trying to get the accuracy of my system after I got my output.json. I am using ` python3 eval_ucf101.py `. I have the val.json( which I assume that it is my output.json) and ucf101_01.json which is annotation file. when I run eval_ucf101.py using these files I am getting the following error. `python3 eval_ucf101.py Traceback (most recent call last): File "eval_ucf101.py", line 157, in <module> ucf_classification = UCFclassification('data/ucf101_01.json', 'data/results/val.json', subset='validation', top_k=1) File "eval_ucf101.py", line 22, in __init__ self.prediction = self._import_prediction(prediction_filename) File "eval_ucf101.py", line 92, in _import_prediction for videoid, v in data['results'].items(): TypeError: list indices must be integers or slices, not str`.

Also, anybody can explain Generate_result_videos function because I am just getting the tested results into another folder called video_pred. Answer to any of these two questions is appreciated.

**Comment by Mohamad73** [comment]
Still looking for an answer for the error,but I got an answer what generate_result_videos function does. It just labels video based on output.json. A rectangle label will be shown at the left upper corner in the result video.Answered by Newbeeyoung
